### ISSUE TITLE
you did not mention the schema for your events application 

### ISSUE THREAD

**Issue by rizwan92** [aws-samples/aws-mobile-appsync-events-starter-react#10]
hii i am learning appsync you put all the code but where is your schema of events so i could check this repository is working or not .

**Comment by manueliglesias** [comment]
Hi @rizwan92 

Thank you for trying this starter! The schema this app uses is the sample schema generated from the AWS AppSync console when you create an api and select "Sample schema" as the template.

![screen shot 2018-03-13 at 2 42 37 pm](https://user-images.githubusercontent.com/6154160/37371525-e0ddc832-26cc-11e8-8835-1daa8457a505.png)
