### ISSUE TITLE
Cannot read property 'subscription' of undefined

### ISSUE THREAD

**Issue by ra8ga** [aws-samples/aws-mobile-appsync-events-starter-react#12]
Hi, I subscriptions does not work.
In the console i get this error:

index.js:2177 Unhandled GraphQL subscription error TypeError: Cannot read property 'subscription' of undefined
    at SubscriptionHandshakeLink._this.request (subscription-handshake-link.js:56)
    at link.js:43
    at index.js:20

**Comment by codylandry** [comment]
@ra8ga Did you find a solution for this? I'm having this issue as well.

**Comment by ra8ga** [comment]
As i remember it was some stupid mistake. It was my fault. I cannot remember what it was :( Sorry.
Next time I'll write more than // edit: my bad and close issuse :(

**Comment by cbaron** [comment]
@codylandry -- what say you?

**Comment by codylandry** [comment]
@cbaron I haven’t solved it. I’m using pollainterval in the meantime till I find an answer.

**Comment by codylandry** [comment]
@cbaron, are you by chance using IAM auth?  The example is using api key. Wondering if the issue might be specific to that.

**Comment by cbaron** [comment]
No, I am using cognito.  However, I am using something from serverless: https://github.com/serverless/serverless-graphql/tree/master/app-client/appsync-client

**Comment by undefobj** [comment]
@codylandry @cbaron Could you open a new issue if you're still having trouble? When you do can you show some sample code with your GraphQL schema and client subscription calls?

**Comment by cbaron** [comment]
I figured out my issue.  Using the debugger I noticed an error object being generated in node_modules/aws-appsync/lib/link/subscription-handshake-link.js.  I tracked it down to a problem with the resolvers in appsync.  This is a bug aws should address for more transparent error handling.

**Comment by codylandry** [comment]
@cbaron Awesome, thanks for posting that.  Yeah, I'd expect a better error if the issue is in the resolver.

**Comment by Gbahaa** [comment]
Hi, 
I had the same problem. The reason was in my subscription type. The return type of a subscription field had ! (i.e. null is not allowed). By removing that, it worked from appsync schema, it worked.

**Comment by codylandry** [comment]
Yeah, I’m hoping to find time to put in a pr.  Basically the appsync client is eating subscription errors.
