### ISSUE TITLE
Some Strange Behavior after initial setup

### ISSUE THREAD

**Issue by allain** [aws-samples/aws-mobile-appsync-events-starter-react#14]
Following along with instructions when the app runs I see:

1. Adding event causes 2 events to appear for half a second then it disappears
2. Commenting causes 2 comments to appear (only 1 is actually created in DynamoDB), and then after 2 seconds or so the entire event screen clears out and becomes a single "Back to Events" button.
3. Clicking on the button takes me back to the events listing but no event is displayed
4. Clicking the browser's Refresh Button makes the event appear again.
5. Attempting to add another comment cause the error below to be thrown:

Uncaught TypeError: Cannot read property 'comments' of undefined
    at Object.props (EventComments.js:63)

If it helps I'm running `npm start` in node v8.9.1 and my browser is "Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on LinuxMint 18.2 (64-bit)"

Thanks

**Comment by manueliglesias** [comment]
Hi @allain

Thanks for trying this sample! Could you please check if you get the same behavior after deleting your node_modules and re install using yarn?

**Comment by allain** [comment]
Thanks for responding.

Using yarn 1.5.1 on first run I'm getting:

```
./node_modules/react-apollo/react-apollo.browser.umd.js
Module not found: Can't resolve 'apollo-client' in '/home/allain/fq/aws-mobile-appsync-events-starter-react/node_modules/react-apollo'
```

Unfortunately after `yarn add apollo-client` it runs but the problems in the issue still persist.

**Comment by ozby** [comment]
i am also encountering same issue

**Comment by vilius-rugaitis** [comment]
I am also experiencing this problem. Would be great, if it would be fixed quickly.

**Comment by manueliglesias** [comment]
Hey, can you guys try again with the recently added yarn.lock ?

Feel free to re-open if needed

**Comment by vilius-rugaitis** [comment]
I just tried the new yarn file and some sources point to localhost. Shouldn't be right?
`error An unexpected error occurred: "http://localhost:4873/aws-appsync/-/aws-appsync-1.0.12.tgz: connect ECONNREFUSED 127.0.0.1:4873".`

**Comment by allain** [comment]
same error here

**Comment by elorzafe** [comment]
Hi @allain and @vilius-rugaitis I have updated both lock files. 

Please let me know how it goes

**Comment by erezrokah** [comment]
I'm having the same issue with latest code from master (duplicates events and comments).
I had the `Uncaught TypeError: Cannot read property 'comments' of undefined
at Object.props (EventComments.js:63)` error as well but can't reproduce at the moment.

I'm pretty new to `apollo`, `GraphQL` and the optimistic response mechanism, but shouldn't setting an `id` on the client (using `uuid`), updating the cache based on that `id`, then updating again based on the response from the server (which auto generates a different `id`) might cause the duplication?

Regarding the `Uncaught TypeError:` it seems like a timing issue where the `data` is set to an empty object for a brief moment. 
If `react` happens to perform a render cycle while the `data` object is empty you get that error.
I haven't been able to figure out the reason for that yet.

**Comment by elorzafe** [comment]
Hi @erezrokah did you use yarn or npm install?

**Comment by erezrokah** [comment]
@elorzafe I tried both (removed `node_modules` before each time).
Currently using `yarn install`.
Also cleared the browser cache.
It is more evident once you have more than 3 events or so.

**Comment by burmisov** [comment]
Same bug here after precisely following all the instructions
![bug](https://user-images.githubusercontent.com/6077619/38987570-f1d93378-43d8-11e8-808c-3300c487d265.gif)

**Comment by erezrokah** [comment]
@elorzafe can we get an update regarding this issue?

**Comment by kzima** [comment]
@manueliglesias has this been fixed?

**Comment by pachomski** [comment]
@manueliglesias  has this been fixed?
