### ISSUE TITLE
How to set Access token in request header?

### ISSUE THREAD

**Issue by DhruvKumarJha** [aws-samples/aws-mobile-appsync-events-starter-react#2]
I am using `AMAZON_COGNITO_USER_POOLS` for authentication and my `apiKey` is set as undefined.

After getting the access token, How and where can I set it so its sent along with the request.

For now when I try to access my GraphQL Endpoint, I am getting
`{"message":"Missing authorization header"}`

**Comment by manueliglesias** [comment]
Hi @DhruvKumarJha , 

Thank you for trying AppSync and this starter app! 

Your JWT token would be passed in the client constructor like this:

```javascript
import AWSAppSyncClient from "aws-appsync";
import appSyncConfig from "./AppSync";

const jwtToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ';

const client = new AWSAppSyncClient({
  url: appSyncConfig.graphqlEndpoint,
  region: appSyncConfig.region,
  auth: {
    type: appSyncConfig.authenticationType,
    jwtToken: jwtToken,
  }
});
```

Let us know if you still have problems. Please feel free to re-open this issue if needed.

**Comment by DhruvKumarJha** [comment]
Thanks, I tried this already.

It works if I set it when the app is being initialized (first load/reload) But I cannot set it dynamically later on.

Ex: If the user is not logged in, I redirect the user to login page, user logs in and I get the token (I verified it and its correct) but then I cannot set it in the client.. And calling the GraphQL endpoint fails.

I tried setting it like this as well

```
jwtToken: functionToGetToken()
```

But this `functionToGetToken` function never gets called while making GraphQL requests. (gets called only on load/reload)

**Comment by manueliglesias** [comment]
@DhruvKumarJha can you try with the latest version in npm ? `npm i aws-appsync@latest`

```javascript
jwtToken: functionToGetToken() // Should work now
```

**Comment by DhruvKumarJha** [comment]
Tried, still doesn't work. `functionToGetToken` gets called only for the first time.

I updated both `aws-appsync` and `aws-appsync-react`.

And now I am getting this new error

```
index.js:2177 Warning: Failed context type: Invalid context `client` of type `AWSAppSyncClient` supplied to `Rehydrated`, expected instance of `AWSAppSyncClient`.
    in Rehydrated (at App.js:73)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider (at App.js:72)
    in WithProvider (at index.js:7)
```

Screenshot:

![screenshot123](https://user-images.githubusercontent.com/13752798/34370682-0f57b5aa-eaec-11e7-99f1-bede3a9b4323.jpg)

**Comment by DhruvKumarJha** [comment]
Got it working, I was actually calling the function `jwtToken: functionToGetToken()` rather than passing it as function name `jwtToken: functionToGetToken`

As soon as I saw your committed code I changed it and it worked.

**Rehydrated** issue still persists.

Thank you.

**Comment by gyandeeps** [comment]
Having same issue and this is how i have it setup:

```js
jwtToken: async () =>
                (await Auth.currentSession()).getAccessToken().getJwtToken()
```

I get error
``` 
"UnauthorizedException"
message:"Missing authorization header"
```

**Comment by gyandeeps** [comment]
since i am passing my own `link` that what was creating a problem. If you use `apollo-link-state` for client state then you need make the call like this

```js
import AWSAppSyncClient, { createAppSyncLink } from "aws-appsync";

const authConfig = {
    type: appSyncAtrributes.authenticationType,

    // COGNITO USER POOLS
    jwtToken: async () => {
        return (await Auth.currentSession()).getAccessToken().getJwtToken();
    }
};

// AppSync client instantiation
const client = new AWSAppSyncClient(
    {
        disableOffline: true,
        url: appSyncAtrributes.graphqlEndpoint,
        region: appSyncAtrributes.region,
        auth: authConfig,
        complexObjectsCredentials: () => Auth.currentCredentials()
    },
    {
        cache,
        link: ApolloLink.from([
            stateLink,
            createAppSyncLink({
                url: appSyncAtrributes.graphqlEndpoint,
                region: appSyncAtrributes.region,
                auth: authConfig,
                complexObjectsCredentials: () => Auth.currentCredentials()
            })
        ])
    }
);
```
