### ISSUE TITLE
Where is schema file?

### ISSUE THREAD

**Issue by medvedevden1s** [aws-samples/aws-mobile-appsync-events-starter-react#22]

**Comment by haverchuck** [comment]
Hi @medvedevden1s 

Thanks for reaching out.  The schema file can be found in the AppSync console. 

When in the console, select your API then select 'Schema' in the sidebar.  You will then have the option of viewing the schema in a GraphiQL-like interface or exporting it to a file.

I'm closing this issue now - but please let us know if you're question is not answered.
