### ISSUE TITLE
Double Mutation - React js example

### ISSUE THREAD

**Issue by enghwa** [aws-samples/aws-mobile-appsync-events-starter-react#9]
Seeing this error when i did a single event creation.
anyone experience the same?

![image](https://user-images.githubusercontent.com/7866724/36855424-5eb8dee0-1dae-11e8-8eb1-8d2d390a3047.png)

**Comment by manueliglesias** [comment]
Hi @enghwa 

thank you for trying the sample app! Can you retry with the latest? I just pushed a couple of commits that address this issue.

Feel free to re-open if you are still facing issues

**Comment by enghwa** [comment]
this is fixed. Thanks.
but if u do a offline-> create new record->online.. the GUI still briefly shows 2 entries although there is no errror on the console.
